"EPSG:28992":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:7931"
    - "EPSG:7930"
    - "EPSG:9286"
    - "EPSG:7912"
    - "EPSG:7789"
    - "OGC:CRS84h"
    - "EPSG:4979"
    - "EPSG:9754"
    - "EPSG:9753"
  uri: http://www.opengis.net/def/crs/EPSG/0/28992
"EPSG:4258":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:7931"
    - "EPSG:7930"
    - "EPSG:9286"
    - "EPSG:7912"
    - "EPSG:7789"
    - "OGC:CRS84h"
    - "EPSG:4979"
    - "EPSG:9754"
    - "EPSG:9753"
  uri: http://www.opengis.net/def/crs/EPSG/0/4258
"EPSG:4936":
  exclude-transformations:
    - "EPSG:7789"
  uri: http://www.opengis.net/def/crs/EPSG/0/4936
"EPSG:3035":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:7931"
    - "EPSG:7930"
    - "EPSG:9286"
    - "EPSG:7912"
    - "EPSG:7789"
    - "OGC:CRS84h"
    - "EPSG:4979"
    - "EPSG:9754"
    - "EPSG:9753"
  uri: http://www.opengis.net/def/crs/EPSG/0/3035
"EPSG:3034":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:7931"
    - "EPSG:7930"
    - "EPSG:9286"
    - "EPSG:7912"
    - "EPSG:7789"
    - "OGC:CRS84h"
    - "EPSG:4979"
    - "EPSG:9754"
    - "EPSG:9753"
  uri: http://www.opengis.net/def/crs/EPSG/0/3034
"EPSG:3043":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:7931"
    - "EPSG:7930"
    - "EPSG:9286"
    - "EPSG:7912"
    - "EPSG:7789"
    - "OGC:CRS84h"
    - "EPSG:4979"
    - "EPSG:9754"
    - "EPSG:9753"
  uri: http://www.opengis.net/def/crs/EPSG/0/3043
"EPSG:3044":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:7931"
    - "EPSG:7930"
    - "EPSG:9286"
    - "EPSG:7912"
    - "EPSG:7789"
    - "OGC:CRS84h"
    - "EPSG:4979"
    - "EPSG:9754"
    - "EPSG:9753"
  uri: http://www.opengis.net/def/crs/EPSG/0/3044
"EPSG:9067":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:7931"
    - "EPSG:7930"
    - "EPSG:9286"
    - "EPSG:7912"
    - "EPSG:7789"
    - "OGC:CRS84h"
    - "EPSG:4979"
    - "EPSG:9754"
    - "EPSG:9753"
  uri: http://www.opengis.net/def/crs/EPSG/0/9067
"EPSG:9000":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:7931"
    - "EPSG:7930"
    - "EPSG:9286"
    - "EPSG:7912"
    - "EPSG:7789"
    - "OGC:CRS84h"
    - "EPSG:4979"
    - "EPSG:9754"
    - "EPSG:9753"
  uri: http://www.opengis.net/def/crs/EPSG/0/9000
"EPSG:7789":
  exclude-transformations:
    - "EPSG:4936"
  uri: http://www.opengis.net/def/crs/EPSG/0/7789
"EPSG:4326":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:7931"
    - "EPSG:7930"
    - "EPSG:9286"
    - "EPSG:7912"
    - "EPSG:7789"
    - "OGC:CRS84h"
    - "EPSG:4979"
    - "EPSG:9754"
    - "EPSG:9753"
  uri: http://www.opengis.net/def/crs/EPSG/0/4326
"OGC:CRS84":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:7931"
    - "EPSG:7930"
    - "EPSG:9286"
    - "EPSG:7912"
    - "EPSG:7789"
    - "OGC:CRS84h"
    - "EPSG:4979"
    - "EPSG:9754"
    - "EPSG:9753"
  uri: http://www.opengis.net/def/crs/OGC/0/CRS84
"EPSG:9755":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:7931"
    - "EPSG:7930"
    - "EPSG:9286"
    - "EPSG:7912"
    - "EPSG:7789"
    - "OGC:CRS84h"
    - "EPSG:4979"
    - "EPSG:9754"
    - "EPSG:9753"
  uri: http://www.opengis.net/def/crs/EPSG/0/9755
"EPSG:3857":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:7931"
    - "EPSG:7930"
    - "EPSG:9286"
    - "EPSG:7912"
    - "EPSG:7789"
    - "OGC:CRS84h"
    - "EPSG:4979"
    - "EPSG:9754"
    - "EPSG:9753"
  uri: http://www.opengis.net/def/crs/EPSG/0/3857
"EPSG:32631":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:7931"
    - "EPSG:7930"
    - "EPSG:9286"
    - "EPSG:7912"
    - "EPSG:7789"
    - "OGC:CRS84h"
    - "EPSG:4979"
    - "EPSG:9754"
    - "EPSG:9753"
  uri: http://www.opengis.net/def/crs/EPSG/0/32631
"EPSG:32632":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:7931"
    - "EPSG:7930"
    - "EPSG:9286"
    - "EPSG:7912"
    - "EPSG:7789"
    - "OGC:CRS84h"
    - "EPSG:4979"
    - "EPSG:9754"
    - "EPSG:9753"
  uri: http://www.opengis.net/def/crs/EPSG/0/32632
"EPSG:4937":
  exclude-transformations: []
  uri: http://www.opengis.net/def/crs/EPSG/0/4937
"EPSG:4979":
  exclude-transformations: []
  uri: http://www.opengis.net/def/crs/EPSG/0/4979
"EPSG:7415":
  exclude-transformations: []
  uri: http://www.opengis.net/def/crs/EPSG/0/7415
"EPSG:7912":
  exclude-transformations: []
  uri: http://www.opengis.net/def/crs/EPSG/0/7912
"EPSG:7930":
  exclude-transformations: []
  uri: http://www.opengis.net/def/crs/EPSG/0/7930
"EPSG:7931":
  exclude-transformations: []
  uri: http://www.opengis.net/def/crs/EPSG/0/7931
"EPSG:9286":
  exclude-transformations: []
  uri: http://www.opengis.net/def/crs/EPSG/0/9286
"EPSG:9753":
  exclude-transformations: []
  uri: http://www.opengis.net/def/crs/EPSG/0/9753
"EPSG:9754":
  exclude-transformations: []
  uri: http://www.opengis.net/def/crs/EPSG/0/9754
"OGC:CRS84h":
  exclude-transformations: []
  uri: http://www.opengis.net/def/crs/OGC/0/CRS84h
"NSGI:DPnet_Bonaire":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:28992"
    - "EPSG:4258"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:3035"
    - "EPSG:3034"
    - "EPSG:3043"
    - "EPSG:3044"
    - "EPSG:7931"
    - "EPSG:9067"
    - "EPSG:7930"
    - "EPSG:7432"
    - "EPSG:7423"
    - "EPSG:9423"
    - "EPSG:9289"
  uri: http://www.nsgi.nl/def/crs/NSGI/0/DPnet_Bonaire
"NSGI:DPnet_Saba":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:28992"
    - "EPSG:4258"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:3035"
    - "EPSG:3034"
    - "EPSG:3043"
    - "EPSG:3044"
    - "EPSG:7931"
    - "EPSG:9067"
    - "EPSG:7930"
    - "EPSG:7432"
    - "EPSG:7423"
    - "EPSG:9423"
    - "EPSG:9289"
  uri: http://www.nsgi.nl/def/crs/NSGI/0/DPnet_Saba
"NSGI:DPnet_StEustatius":
  exclude-transformations:
    - "EPSG:7415"
    - "EPSG:28992"
    - "EPSG:4258"
    - "EPSG:4937"
    - "EPSG:4936"
    - "EPSG:3035"
    - "EPSG:3034"
    - "EPSG:3043"
    - "EPSG:3044"
    - "EPSG:7931"
    - "EPSG:9067"
    - "EPSG:7930"
    - "EPSG:7432"
    - "EPSG:7423"
    - "EPSG:9423"
    - "EPSG:9289"
  uri: http://www.nsgi.nl/def/crs/NSGI/0/DPnet_StEustatius
