transformations:
  exclude:
    EPSG:28992:
      [
        EPSG:7415,
        EPSG:4937,
        EPSG:4936,
        EPSG:7931,
        EPSG:7930,
        EPSG:9286,
        EPSG:7912,
        EPSG:7789,
        OGC:CRS84h,
        EPSG:4979,
        EPSG:9754,
        EPSG:9753,
      ]
    EPSG:4258:
      [
        EPSG:7415,
        EPSG:4937,
        EPSG:4936,
        EPSG:7931,
        EPSG:7930,
        EPSG:9286,
        EPSG:7912,
        EPSG:7789,
        OGC:CRS84h,
        EPSG:4979,
        EPSG:9754,
        EPSG:9753,
      ]
    EPSG:4936: [EPSG:7789]
    EPSG:3035:
      [
        EPSG:7415,
        EPSG:4937,
        EPSG:4936,
        EPSG:7931,
        EPSG:7930,
        EPSG:9286,
        EPSG:7912,
        EPSG:7789,
        OGC:CRS84h,
        EPSG:4979,
        EPSG:9754,
        EPSG:9753,
      ]
    EPSG:3034:
      [
        EPSG:7415,
        EPSG:4937,
        EPSG:4936,
        EPSG:7931,
        EPSG:7930,
        EPSG:9286,
        EPSG:7912,
        EPSG:7789,
        OGC:CRS84h,
        EPSG:4979,
        EPSG:9754,
        EPSG:9753,
      ]
    EPSG:3043:
      [
        EPSG:7415,
        EPSG:4937,
        EPSG:4936,
        EPSG:7931,
        EPSG:7930,
        EPSG:9286,
        EPSG:7912,
        EPSG:7789,
        OGC:CRS84h,
        EPSG:4979,
        EPSG:9754,
        EPSG:9753,
      ]
    EPSG:3044:
      [
        EPSG:7415,
        EPSG:4937,
        EPSG:4936,
        EPSG:7931,
        EPSG:7930,
        EPSG:9286,
        EPSG:7912,
        EPSG:7789,
        OGC:CRS84h,
        EPSG:4979,
        EPSG:9754,
        EPSG:9753,
      ]
    EPSG:9067:
      [
        EPSG:7415,
        EPSG:4937,
        EPSG:4936,
        EPSG:7931,
        EPSG:7930,
        EPSG:9286,
        EPSG:7912,
        EPSG:7789,
        OGC:CRS84h,
        EPSG:4979,
        EPSG:9754,
        EPSG:9753,
      ]
    EPSG:9000:
      [
        EPSG:7415,
        EPSG:4937,
        EPSG:4936,
        EPSG:7931,
        EPSG:7930,
        EPSG:9286,
        EPSG:7912,
        EPSG:7789,
        OGC:CRS84h,
        EPSG:4979,
        EPSG:9754,
        EPSG:9753,
      ]
    EPSG:7789: [EPSG:4936]
    EPSG:4326:
      [
        EPSG:7415,
        EPSG:4937,
        EPSG:4936,
        EPSG:7931,
        EPSG:7930,
        EPSG:9286,
        EPSG:7912,
        EPSG:7789,
        OGC:CRS84h,
        EPSG:4979,
        EPSG:9754,
        EPSG:9753,
      ]
    OGC:CRS84:
      [
        EPSG:7415,
        EPSG:4937,
        EPSG:4936,
        EPSG:7931,
        EPSG:7930,
        EPSG:9286,
        EPSG:7912,
        EPSG:7789,
        OGC:CRS84h,
        EPSG:4979,
        EPSG:9754,
        EPSG:9753,
      ]
    EPSG:9755:
      [
        EPSG:7415,
        EPSG:4937,
        EPSG:4936,
        EPSG:7931,
        EPSG:7930,
        EPSG:9286,
        EPSG:7912,
        EPSG:7789,
        OGC:CRS84h,
        EPSG:4979,
        EPSG:9754,
        EPSG:9753,
      ]
    EPSG:3857:
      [
        EPSG:7415,
        EPSG:4937,
        EPSG:4936,
        EPSG:7931,
        EPSG:7930,
        EPSG:9286,
        EPSG:7912,
        EPSG:7789,
        OGC:CRS84h,
        EPSG:4979,
        EPSG:9754,
        EPSG:9753,
      ]
    EPSG:32631:
      [
        EPSG:7415,
        EPSG:4937,
        EPSG:4936,
        EPSG:7931,
        EPSG:7930,
        EPSG:9286,
        EPSG:7912,
        EPSG:7789,
        OGC:CRS84h,
        EPSG:4979,
        EPSG:9754,
        EPSG:9753,
      ]
    EPSG:32632:
      [
        EPSG:7415,
        EPSG:4937,
        EPSG:4936,
        EPSG:7931,
        EPSG:7930,
        EPSG:9286,
        EPSG:7912,
        EPSG:7789,
        OGC:CRS84h,
        EPSG:4979,
        EPSG:9754,
        EPSG:9753,
      ]
