repos:
    # - repo: https://github.com/adrienverge/yamllint.git
    #   rev: v1.35.1
    #   hooks:
    #     - id: yamllint
    #       args: [--strict]
    # - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    #   rev: 0.2.3 # or other specific tag
    #   hooks:
    #     - id: yamlfmt
    #       args: [--mapping, '2', --sequence, '4', --offset, '2', --width, '150']
    - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
      rev: v0.6.9
      hooks:
        # Run the linter.
        - id: ruff
          args: [ --fix ]
        # Run the formatter.
        - id: ruff-format
