[[repos]]
repo = "https://github.com/hadolint/hadolint"
rev = "v2.12.0"
[[repos.hooks]]
id = "hadolint"


[[repos]]
repo = "https://github.com/google/yamlfmt"
rev = "v0.13.0"
[[repos.hooks]]
id = "yamlfmt"
args = []


[[repos]]
repo = "https://github.com/adrienverge/yamllint.git"
rev = "v1.35.1"
[[repos.hooks]]
id = "yamllint"
args = [ "--strict", "-c", ".yamllint",]


[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.6.9"
[[repos.hooks]]
id = "ruff"
args = [ "--fix",]

[[repos.hooks]]
id = "ruff-format"


[[repos]]
repo = "local"
[[repos.hooks]]
id = "pytest-check"
name = "pytest-check"
stages = [ "pre-commit",]
types = [ "python",]
entry = "pytest"
language = "system"
pass_filenames = false
args = [ "-v", "-k", "not validation", "tests",]


[[repos]]
repo = "https://github.com/executablebooks/mdformat"
rev = "0.7.17"
[[repos.hooks]]
id = "mdformat"
additional_dependencies = [ "mdformat-gfm",]


