[project]
name = "coordinates-transformation-api"
description = "Coordinates transformation API of the Nederlandse Samenwerking Geodetische Infrastructuur (NSGI)"
keywords = ["NSGI", "pyproj", "fastapi", "coordinates", "geo"]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
]
readme = { file = "./README.md", content-type = "text/markdown" }
dependencies = [
    "fastapi == 0.100.1",
    "uvicorn == 0.23.2",
    "pyyaml == 5.3.1",
    "geojson_pydantic == 1.0.0",
    "pyproj == 3.6.0",
    "pydantic-settings == 2.0.2",
    "email-validator == 2.0.0",
]
requires-python = ">=3.11.4"
dynamic = ["version"]

[project.optional-dependencies]
dev = ["black", "autoflake", "isort", "mypy"]


[build-system]
requires = ["setuptools>=61.0", "setuptools-git-versioning<2"]
build-backend = "setuptools.build_meta"

[project.scripts]
ct-api = "coordinates_transformation_api.main:main"

[tool.setuptools-git-versioning]
enabled = true


[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)
include = ["coordinates_transformation_api*"]  # package names should match these glob patterns (["*"] by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)

[tool.setuptools.package-data]
"coordinates_transformation_api.assets" = ["*"]
"coordinates_transformation_api.assets.static" = ["*"]
