uri:
  - "http://www.nsgi.nl/def/crs/NSGI/0/Bonaire_DPnet"
  - "http://www.nsgi.nl/def/crs/NSGI/0/Bonaire_DPnet_KADpeil"
  - "http://www.nsgi.nl/def/crs/NSGI/0/Bonaire2004_GEOGRAPHIC_2D"
  - "http://www.nsgi.nl/def/crs/NSGI/0/Bonaire2004_GEOGRAPHIC_3D"
  - "http://www.nsgi.nl/def/crs/NSGI/0/Bonaire2004_GEOCENTRIC"
  - "http://www.opengis.net/def/crs/EPSG/0/32619"
  - "http://www.opengis.net/def/crs/EPSG/0/32620"
  - "http://www.opengis.net/def/crs/EPSG/0/9000"
  - "http://www.opengis.net/def/crs/EPSG/0/4326"
  - "http://www.opengis.net/def/crs/OGC/0/CRS84"
  - "http://www.opengis.net/def/crs/EPSG/0/7912"
  - "http://www.opengis.net/def/crs/EPSG/0/4979"
  - "http://www.opengis.net/def/crs/OGC/0/CRS84h"
  - "http://www.opengis.net/def/crs/EPSG/0/7789"
