uri:
  - "http://www.opengis.net/def/crs/EPSG/0/28992"
  - "http://www.opengis.net/def/crs/EPSG/0/9286"
  - "http://www.opengis.net/def/crs/EPSG/0/9289"
  - "http://www.opengis.net/def/crs/EPSG/0/3043"
  - "http://www.opengis.net/def/crs/EPSG/0/3044"
  - "http://www.opengis.net/def/crs/EPSG/0/3034"
  - "http://www.opengis.net/def/crs/EPSG/0/3035"
  - "http://www.opengis.net/def/crs/EPSG/0/3857"
  - "http://www.opengis.net/def/crs/EPSG/0/32631"
  - "http://www.opengis.net/def/crs/EPSG/0/32632"
  - "http://www.opengis.net/def/crs/EPSG/0/7415"
  - "http://www.opengis.net/def/crs/EPSG/0/9067"
  - "http://www.opengis.net/def/crs/EPSG/0/4258"
  - "http://www.opengis.net/def/crs/EPSG/0/9000"
  - "http://www.opengis.net/def/crs/EPSG/0/4326"
  - "http://www.opengis.net/def/crs/OGC/0/CRS84"
  - "http://www.opengis.net/def/crs/EPSG/0/7931"
  - "http://www.opengis.net/def/crs/EPSG/0/4937"
  - "http://www.opengis.net/def/crs/EPSG/0/7912"
  - "http://www.opengis.net/def/crs/EPSG/0/4979"
  - "http://www.opengis.net/def/crs/OGC/0/CRS84h"
  - "http://www.opengis.net/def/crs/EPSG/0/7930"
  - "http://www.opengis.net/def/crs/EPSG/0/4936"
  - "http://www.opengis.net/def/crs/EPSG/0/7789"
